export const FETCH_ACCOUNT = 'FETCH_ACCOUNT'
export const FETCH_ACCOUNTS = 'FETCH_ACCOUNTS'
export const FETCH_ACCOUNT_ENTRIES = 'FETCH_ACCOUNT_ENTRIES'

export const FETCH_INVOICE = 'FETCH_INVOICE'
export const FETCH_INVOICES = 'FETCH_INVOICES'


export const FETCH_SALES = 'FETCH_SALES'

export const PURCHASE_INVENTORY = 'PURCHASE_INVENTORY'
export const FETCH_INVENTORIES = 'FETCH_INVENTORIES'